require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RapperSongsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # RapperSong. As you add validations to RapperSong, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "rapper" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RapperSongsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all rapper_songs as @rapper_songs" do
      rapper_song = RapperSong.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:rapper_songs)).to eq([rapper_song])
    end
  end

  describe "GET show" do
    it "assigns the requested rapper_song as @rapper_song" do
      rapper_song = RapperSong.create! valid_attributes
      get :show, {:id => rapper_song.to_param}, valid_session
      expect(assigns(:rapper_song)).to eq(rapper_song)
    end
  end

  describe "GET new" do
    it "assigns a new rapper_song as @rapper_song" do
      get :new, {}, valid_session
      expect(assigns(:rapper_song)).to be_a_new(RapperSong)
    end
  end

  describe "GET edit" do
    it "assigns the requested rapper_song as @rapper_song" do
      rapper_song = RapperSong.create! valid_attributes
      get :edit, {:id => rapper_song.to_param}, valid_session
      expect(assigns(:rapper_song)).to eq(rapper_song)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RapperSong" do
        expect {
          post :create, {:rapper_song => valid_attributes}, valid_session
        }.to change(RapperSong, :count).by(1)
      end

      it "assigns a newly created rapper_song as @rapper_song" do
        post :create, {:rapper_song => valid_attributes}, valid_session
        expect(assigns(:rapper_song)).to be_a(RapperSong)
        expect(assigns(:rapper_song)).to be_persisted
      end

      it "redirects to the created rapper_song" do
        post :create, {:rapper_song => valid_attributes}, valid_session
        expect(response).to redirect_to(RapperSong.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rapper_song as @rapper_song" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(RapperSong).to receive(:save).and_return(false)
        post :create, {:rapper_song => { "rapper" => "invalid value" }}, valid_session
        expect(assigns(:rapper_song)).to be_a_new(RapperSong)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(RapperSong).to receive(:save).and_return(false)
        post :create, {:rapper_song => { "rapper" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rapper_song" do
        rapper_song = RapperSong.create! valid_attributes
        # Assuming there are no other rapper_songs in the database, this
        # specifies that the RapperSong created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(RapperSong).to receive(:update).with({ "rapper" => "MyString" })
        put :update, {:id => rapper_song.to_param, :rapper_song => { "rapper" => "MyString" }}, valid_session
      end

      it "assigns the requested rapper_song as @rapper_song" do
        rapper_song = RapperSong.create! valid_attributes
        put :update, {:id => rapper_song.to_param, :rapper_song => valid_attributes}, valid_session
        expect(assigns(:rapper_song)).to eq(rapper_song)
      end

      it "redirects to the rapper_song" do
        rapper_song = RapperSong.create! valid_attributes
        put :update, {:id => rapper_song.to_param, :rapper_song => valid_attributes}, valid_session
        expect(response).to redirect_to(rapper_song)
      end
    end

    describe "with invalid params" do
      it "assigns the rapper_song as @rapper_song" do
        rapper_song = RapperSong.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(RapperSong).to receive(:update).and_return(false)
        put :update, {:id => rapper_song.to_param, :rapper_song => { "rapper" => "invalid value" }}, valid_session
        expect(assigns(:rapper_song)).to eq(rapper_song)
      end

      it "re-renders the 'edit' template" do
        rapper_song = RapperSong.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(RapperSong).to receive(:update).and_return(false)
        put :update, {:id => rapper_song.to_param, :rapper_song => { "rapper" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rapper_song" do
      rapper_song = RapperSong.create! valid_attributes
      expect {
        delete :destroy, {:id => rapper_song.to_param}, valid_session
      }.to change(RapperSong, :count).by(-1)
    end

    it "redirects to the rapper_songs list" do
      rapper_song = RapperSong.create! valid_attributes
      delete :destroy, {:id => rapper_song.to_param}, valid_session
      expect(response).to redirect_to(rapper_songs_url)
    end
  end

end
